### ISSUE TITLE
请问下添加了ghostnetv2模块后就不显示GFLOPs了，怎么解决啊

### ISSUE THREAD

**Issue by xingguang12** [ZHjiuang/yolov5-ghostv2-SIOU-CA-WBF-V6.2#2]
![20240313084437](https://github.com/ZHjiuang/yolov5-ghostnetv2-SIOU-CA-WBF-V6.2/assets/57353111/11f7e532-e751-421b-8fc7-9ffc1164565e)

**Comment by xingguang12** [comment]
@ZHjiuang 求解答

**Comment by ZHjiuang** [comment]
打开yolo.py，将--cfg改为模型的yaml文件，--line-profile改为default=True，然后运行yolo.py

**Comment by xingguang12** [comment]
![20240314194135](https://github.com/ZHjiuang/yolov5-ghostnetv2-SIOU-CA-WBF-V6.2/assets/57353111/33c5a187-b4e4-4028-8348-19364124d6bc)
            from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     10424  models.common.C3Ghost1                  [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2     45280  models.common.C3Ghost1                  [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    192672  models.common.C3Ghost1                  [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    599488  models.common.C3Ghost1                  [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1    229245  Detect                                  [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
YOLOv5s-ghostv2 summary: 382 layers, 6140853 parameters, 6140853 gradients

@ZHjiuang  试过了没用啊，哥，还有什么方法吗

**Comment by ZHjiuang** [comment]
` time (ms)     GFLOPs     params  module
     39.63       0.73       3520  models.common.Conv
     36.82       0.53      10144  models.common.GhostConv
     85.06       0.52      10424  models.common.C3Ghost
     18.56       0.50      38720  models.common.GhostConv
     55.92       0.54      45280  models.common.C3Ghost
      9.95       0.49     151168  models.common.GhostConv
     39.98       0.56     192672  models.common.C3Ghost
      7.76       0.48     597248  models.common.GhostConv
     12.75       0.46     599488  models.common.C3Ghost
      2.00       0.00      25648  models.common.CoordAtt
     19.11       0.53     656896  models.common.SPPF
      2.20       0.06      69248  models.common.GhostConv
      1.00       0.00          0  torch.nn.modules.upsampling.Upsample
      1.60       0.00          0  models.common.Concat
     24.70       0.68     217824  models.common.C3Ghost
      4.30       0.06      18240  models.common.GhostConv
      1.80       0.00          0  torch.nn.modules.upsampling.Upsample
      2.85       0.00          0  models.common.Concat
     43.02       0.70      55664  models.common.C3Ghost
      6.20       0.24      75584  models.common.GhostConv
      0.80       0.00          0  models.common.Concat
     22.61       0.47     152288  models.common.C3Ghost
      5.15       0.24     298624  models.common.GhostConv
      0.00       0.00          0  models.common.Concat
     13.41       0.46     599488  models.common.C3Ghost
      4.70       0.07      21576  Detect
    461.92       8.31    3839744  Total

进程已结束，退出代码为 0
` 紧接着就会打印每层的GFLOPs

**Comment by xingguang12** [comment]
time (ms)     GFLOPs     params  module
     18.20       0.73       3520  models.common.Conv
      0.40       0.96      18560  models.common.Conv
      1.80       0.52      10424  models.common.C3Ghost1
      0.30       0.95      73984  models.common.Conv
      2.25       0.54      45280  models.common.C3Ghost1
      0.20       0.95     295424  models.common.Conv
      3.50       0.56     192672  models.common.C3Ghost1
      0.30       0.95    1180672  models.common.Conv
      1.15       0.46     599488  models.common.C3Ghost1
      0.50       0.53     656896  models.common.SPPF
      0.10       0.11     131584  models.common.Conv
      0.10       0.00          0  torch.nn.modules.upsampling.Upsample
      0.00       0.00          0  models.common.Concat
      1.00       1.16     361984  models.common.C3
      0.20       0.11      33024  models.common.Conv
      0.00       0.00          0  torch.nn.modules.upsampling.Upsample
      0.10       0.00          0  models.common.Concat
      1.40       1.17      90880  models.common.C3
      0.30       0.47     147712  models.common.Conv
      0.00       0.00          0  models.common.Concat
      1.50       0.95     296448  models.common.C3
      0.25       0.47     590336  models.common.Conv
      0.10       0.00          0  models.common.Concat
      0.80       0.95    1182720  models.common.C3
      0.40       0.73     229245  Detect
     34.85          -          -  Total

Process finished with exit code 0
我这是要自己加一遍吗 @ZHjiuang

**Comment by ZHjiuang** [comment]
> time (ms) GFLOPs params module 18.20 0.73 3520 models.common.Conv 0.40 0.96 18560 models.common.Conv 1.80 0.52 10424 models.common.C3Ghost1 0.30 0.95 73984 models.common.Conv 2.25 0.54 45280 models.common.C3Ghost1 0.20 0.95 295424 models.common.Conv 3.50 0.56 192672 models.common.C3Ghost1 0.30 0.95 1180672 models.common.Conv 1.15 0.46 599488 models.common.C3Ghost1 0.50 0.53 656896 models.common.SPPF 0.10 0.11 131584 models.common.Conv 0.10 0.00 0 torch.nn.modules.upsampling.Upsample 0.00 0.00 0 models.common.Concat 1.00 1.16 361984 models.common.C3 0.20 0.11 33024 models.common.Conv 0.00 0.00 0 torch.nn.modules.upsampling.Upsample 0.10 0.00 0 models.common.Concat 1.40 1.17 90880 models.common.C3 0.30 0.47 147712 models.common.Conv 0.00 0.00 0 models.common.Concat 1.50 0.95 296448 models.common.C3 0.25 0.47 590336 models.common.Conv 0.10 0.00 0 models.common.Concat 0.80 0.95 1182720 models.common.C3 0.40 0.73 229245 Detect 34.85 - - Total
> 
> Process finished with exit code 0 我这是要自己加一遍吗 @ZHjiuang

![image](https://github.com/ZHjiuang/yolov5-ghostnetv2-SIOU-CA-WBF-V6.2/assets/91889803/76579419-63d5-40eb-abc4-83ee1b0ccfcc)
已经实现了

**Comment by xingguang12** [comment]
![20240314201709](https://github.com/ZHjiuang/yolov5-ghostnetv2-SIOU-CA-WBF-V6.2/assets/57353111/5920d8b4-99e3-4c30-a6d6-fa2948544b5c)
我这里是两个-

**Comment by ZHjiuang** [comment]
> ![20240314201709](https://private-user-images.githubusercontent.com/57353111/312833411-5920d8b4-99e3-4c30-a6d6-fa2948544b5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTg5NTksIm5iZiI6MTcxMDQxODY1OSwicGF0aCI6Ii81NzM1MzExMS8zMTI4MzM0MTEtNTkyMGQ4YjQtOTllMy00YzMwLWE2ZDYtZmEyOTQ4NTQ0YjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEyMTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NDYyNGM4MWEyOGZlNmNiN2FjOWJmOGIyN2IwYjEwOGJjMDRmMThjZDNiOTVlNjQ4ZmNjNGMzNjkxMTQ0YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lzj6H34hR0Mtm3nWSsSOTc3zoa0V8QafRRq6pv7CACw) 我这里是两个-

替换成这个`LOGGER.info(f"{sum(dt):10.2f} {sum(self.do_m):10.2f} {sum(self.dp_m):10.0f}  Total")`

**Comment by xingguang12** [comment]
Traceback (most recent call last):
  File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 392, in <module>
    model(im, profile=True)
  File "C:\Users\fanxiao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 211, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 121, in _forward_once
    self._profile_one_layer(m, x, dt)
  File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 140, in _profile_one_layer
    LOGGER.info(f"{sum(dt):10.2f} {sum(self.do_m):10.2f} {sum(self.dp_m):10.0f}  Total")
  File "C:\Users\fanxiao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DetectionModel' object has no attribute 'do_m'
报错了，哥

**Comment by ZHjiuang** [comment]
> Traceback (most recent call last): File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 392, in model(im, profile=True) File "C:\Users\fanxiao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 211, in forward return self._forward_once(x, profile, visualize) # single-scale inference, train File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 121, in _forward_once self._profile_one_layer(m, x, dt) File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 140, in _profile_one_layer LOGGER.info(f"{sum(dt):10.2f} {sum(self.do_m):10.2f} {sum(self.dp_m):10.0f} Total") File "C:\Users\fanxiao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1207, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'DetectionModel' object has no attribute 'do_m' 报错了，哥

`    def _profile_one_layer(self, m, x, dt):
        c = m == self.model[-1]  # is final layer, copy input as inplace fix
        o = thop.profile(m, inputs=(x.copy() if c else x,), verbose=False)[0] / 1E9 * 2 if thop else 0  # FLOPs
        t = time_sync()
        for _ in range(10):
            m(x.copy() if c else x)
        dt.append((time_sync() - t) * 100)
        self.do_m.append(o)
        self.dp_m.append(m.np)
        if m == self.model[0]:
            LOGGER.info(f"{'time (ms)':>10s} {'GFLOPs':>10s} {'params':>10s}  module")
        LOGGER.info(f'{dt[-1]:10.2f} {o:10.2f} {m.np:10.0f}  {m.type}')

        if c:
            # LOGGER.info(f"{sum(dt):10.2f} {'-':>10s} {'-':>10s}  Total")
            LOGGER.info(f"{sum(dt):10.2f} {sum(self.do_m):10.2f} {sum(self.dp_m):10.0f}  Total")`

**Comment by ZHjiuang** [comment]
> Traceback (most recent call last): File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 392, in model(im, profile=True) File "C:\Users\fanxiao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 211, in forward return self._forward_once(x, profile, visualize) # single-scale inference, train File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 121, in _forward_once self._profile_one_layer(m, x, dt) File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 140, in _profile_one_layer LOGGER.info(f"{sum(dt):10.2f} {sum(self.do_m):10.2f} {sum(self.dp_m):10.0f} Total") File "C:\Users\fanxiao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1207, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'DetectionModel' object has no attribute 'do_m' 报错了，哥

‘ def _profile_one_layer(self, m, x, dt):
      c = m == self.model[-1]  # is final layer, copy input as inplace fix
      o = thop.profile(m, inputs=(x.copy() if c else x,), verbose=False)[0] / 1E9 * 2 if thop else 0  # FLOPs
      t = time_sync()
      for _ in range(10):
          m(x.copy() if c else x)
      dt.append((time_sync() - t) * 100)
      self.do_m.append(o)
      self.dp_m.append(m.np)
      if m == self.model[0]:
          LOGGER.info(f"{'time (ms)':>10s} {'GFLOPs':>10s} {'params':>10s}  module")
      LOGGER.info(f'{dt[-1]:10.2f} {o:10.2f} {m.np:10.0f}  {m.type}')

      if c:
          # LOGGER.info(f"{sum(dt):10.2f} {'-':>10s} {'-':>10s}  Total")
          LOGGER.info(f"{sum(dt):10.2f} {sum(self.do_m):10.2f} {sum(self.dp_m):10.0f}  Total")’

**Comment by ZHjiuang** [comment]
> Traceback (most recent call last): File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 392, in model(im, profile=True) File "C:\Users\fanxiao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 211, in forward return self._forward_once(x, profile, visualize) # single-scale inference, train File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 121, in _forward_once self._profile_one_layer(m, x, dt) File "C:\my_create\python_code\detect\tt100k_2021\imgs\tt100k_v5_format_end\models\yolo.py", line 140, in _profile_one_layer LOGGER.info(f"{sum(dt):10.2f} {sum(self.do_m):10.2f} {sum(self.dp_m):10.0f} Total") File "C:\Users\fanxiao\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1207, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'DetectionModel' object has no attribute 'do_m' 报错了，哥

![image](https://github.com/ZHjiuang/yolov5-ghostnetv2-SIOU-CA-WBF-V6.2/assets/91889803/550aed8d-f4bf-47db-a08b-67fef6850504)
需要稍微改动一下这个函数`_profile_one_layer`

**Comment by xingguang12** [comment]
AttributeError: 'DetectionModel' object has no attribute 'do_m'
同样的错，哥
![20240314203209](https://github.com/ZHjiuang/yolov5-ghostnetv2-SIOU-CA-WBF-V6.2/assets/57353111/9c491c36-c277-4cfa-bf04-fc0bff0bca88)

**Comment by ZHjiuang** [comment]
> AttributeError: 'DetectionModel' object has no attribute 'do_m' 同样的错，哥 ![20240314203209](https://private-user-images.githubusercontent.com/57353111/312838254-9c491c36-c277-4cfa-bf04-fc0bff0bca88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTk4NDUsIm5iZiI6MTcxMDQxOTU0NSwicGF0aCI6Ii81NzM1MzExMS8zMTI4MzgyNTQtOWM0OTFjMzYtYzI3Ny00Y2ZhLWJmMDQtZmMwYmZmMGJjYTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEyMzIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YTJiMTYwODgxMWYzYjI5OGJlYWY1MTNkMzJjZGRhNDNlZThkMjE3MDI4YzAwOWU3MTU4ZDk2YzM5MmI5ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZLLkM0wN_RFJgTCQLmGycmVtcR5koBXHpnBf0UB2FQ)

在这个函数外先定义两个变量`do_m = []‘’dp_m = []`

**Comment by ZHjiuang** [comment]
> AttributeError: 'DetectionModel' object has no attribute 'do_m' 同样的错，哥 ![20240314203209](https://private-user-images.githubusercontent.com/57353111/312838254-9c491c36-c277-4cfa-bf04-fc0bff0bca88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTk4NDUsIm5iZiI6MTcxMDQxOTU0NSwicGF0aCI6Ii81NzM1MzExMS8zMTI4MzgyNTQtOWM0OTFjMzYtYzI3Ny00Y2ZhLWJmMDQtZmMwYmZmMGJjYTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEyMzIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YTJiMTYwODgxMWYzYjI5OGJlYWY1MTNkMzJjZGRhNDNlZThkMjE3MDI4YzAwOWU3MTU4ZDk2YzM5MmI5ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZLLkM0wN_RFJgTCQLmGycmVtcR5koBXHpnBf0UB2FQ)

在这个函数外先定义两个变量`do_m = [] dp_m = []`

**Comment by xingguang12** [comment]
![20240314204505](https://github.com/ZHjiuang/yolov5-ghostnetv2-SIOU-CA-WBF-V6.2/assets/57353111/0e1c16cd-b9fc-4fc6-bb31-0dc944d7522b)
感谢哥，成功了，么么
